package com.yx.base.document;
// Generated 2017-6-29 16:37:22 by Hibernate Tools 5.2.1.Final

import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ImMessage generated by hbm2java
 */
@Document(collection = "ImMessage")
public class ImMessageDoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5210194821587493071L;
	@Id
	private Long id;
	private Integer version;
	private Integer devType;
	private Integer geoId;	
	private String msgId;
	private Long fromId;
	private Integer fromType;
	private String imageIconUrl;
	private Long destId;
	private String fromName;
	private String content;
	private Integer messageType;
	private Long sendTime;
	private Long receiveTime;
	private Integer status;
	private Long belongUserId;

	
	public Long getBelongUserId() {
		return belongUserId;
	}

	public void setBelongUserId(Long belongUserId) {
		this.belongUserId = belongUserId;
	}

	public ImMessageDoc() {
	}

	public ImMessageDoc(Integer devType, Integer geoId, String msgId, Long fromId, Integer fromType, String imageIconUrl,
			Long destId, String fromName, String content, Integer messageType, Long sendTime, Long receiveTime,
			Integer status) {
		this.devType = devType;
		this.geoId = geoId;
		this.msgId = msgId;
		this.fromId = fromId;
		this.fromType = fromType;
		this.imageIconUrl = imageIconUrl;
		this.destId = destId;
		this.fromName = fromName;
		this.content = content;
		this.messageType = messageType;
		this.sendTime = sendTime;
		this.receiveTime = receiveTime;
		this.status = status;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getDevType() {
		return this.devType;
	}

	public void setDevType(Integer devType) {
		this.devType = devType;
	}

	public Integer getGeoId() {
		return this.geoId;
	}

	public void setGeoId(Integer geoId) {
		this.geoId = geoId;
	}

	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	public Long getFromId() {
		return this.fromId;
	}

	public void setFromId(Long fromId) {
		this.fromId = fromId;
	}

	public Integer getFromType() {
		return this.fromType;
	}

	public void setFromType(Integer fromType) {
		this.fromType = fromType;
	}

	public String getImageIconUrl() {
		return this.imageIconUrl;
	}

	public void setImageIconUrl(String imageIconUrl) {
		this.imageIconUrl = imageIconUrl;
	}

	public Long getDestId() {
		return this.destId;
	}

	public void setDestId(Long destId) {
		this.destId = destId;
	}

	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getMessageType() {
		return this.messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	public Long getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Long sendTime) {
		this.sendTime = sendTime;
	}

	public Long getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Long receiveTime) {
		this.receiveTime = receiveTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
