package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImFeedback generated by hbm2java
 */
@Entity
@Table(name = "im_feedback", catalog = "imdb")
public class ImFeedback implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String userName;
	private String userMobile;
	private Long createTime;
	private String feedbackContent;
	private Integer isProcessed;

	public ImFeedback() {
	}

	public ImFeedback(Long userId, String userName, String userMobile, Long createTime, String feedbackContent,
			Integer isProcessed) {
		this.userId = userId;
		this.userName = userName;
		this.userMobile = userMobile;
		this.createTime = createTime;
		this.feedbackContent = feedbackContent;
		this.isProcessed = isProcessed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_mobile")
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "feedback_content", length = 65535)
	public String getFeedbackContent() {
		return this.feedbackContent;
	}

	public void setFeedbackContent(String feedbackContent) {
		this.feedbackContent = feedbackContent;
	}

	@Column(name = "is_processed")
	public Integer getIsProcessed() {
		return this.isProcessed;
	}

	public void setIsProcessed(Integer isProcessed) {
		this.isProcessed = isProcessed;
	}

}
