package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImFeed generated by hbm2java
 */
@Entity
@Table(name = "im_feed", catalog = "imdb")
public class ImFeed implements java.io.Serializable {

	private Long id;
	private String feedText;
	private String feedImgs;
	private Long userId;
	private String userName;
	private String userHeadUrl;
	private Long createTime;
	private Integer status;
	private Set<ImFeedPraise> imFeedPraises = new HashSet<ImFeedPraise>(0);
	private Set<ImFeedComment> imFeedComments = new HashSet<ImFeedComment>(0);

	public ImFeed() {
	}

	public ImFeed(String feedText, String feedImgs, Long userId, String userName, String userHeadUrl, Long createTime,
			Integer status, Set<ImFeedPraise> imFeedPraises, Set<ImFeedComment> imFeedComments) {
		this.feedText = feedText;
		this.feedImgs = feedImgs;
		this.userId = userId;
		this.userName = userName;
		this.userHeadUrl = userHeadUrl;
		this.createTime = createTime;
		this.status = status;
		this.imFeedPraises = imFeedPraises;
		this.imFeedComments = imFeedComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "feed_text", length = 65535)
	public String getFeedText() {
		return this.feedText;
	}

	public void setFeedText(String feedText) {
		this.feedText = feedText;
	}

	@Column(name = "feed_imgs", length = 65535)
	public String getFeedImgs() {
		return this.feedImgs;
	}

	public void setFeedImgs(String feedImgs) {
		this.feedImgs = feedImgs;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_head_url")
	public String getUserHeadUrl() {
		return this.userHeadUrl;
	}

	public void setUserHeadUrl(String userHeadUrl) {
		this.userHeadUrl = userHeadUrl;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imFeed")
	public Set<ImFeedPraise> getImFeedPraises() {
		return this.imFeedPraises;
	}

	public void setImFeedPraises(Set<ImFeedPraise> imFeedPraises) {
		this.imFeedPraises = imFeedPraises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imFeed")
	public Set<ImFeedComment> getImFeedComments() {
		return this.imFeedComments;
	}

	public void setImFeedComments(Set<ImFeedComment> imFeedComments) {
		this.imFeedComments = imFeedComments;
	}

}
