package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImFeedComment generated by hbm2java
 */
@Entity
@Table(name = "im_feed_comment", catalog = "imdb")
public class ImFeedComment implements java.io.Serializable {

	private Long id;
	private ImFeed imFeed;
	private Long userId;
	private String userName;
	private String userHeadUrl;
	private Long replyUserId;
	private String replyUserName;
	private String replyUserHeadUrl;
	private String commentText;
	private Long createTime;

	public ImFeedComment() {
	}

	public ImFeedComment(ImFeed imFeed, Long userId, String userName, String userHeadUrl, Long replyUserId,
			String replyUserName, String replyUserHeadUrl, String commentText, Long createTime) {
		this.imFeed = imFeed;
		this.userId = userId;
		this.userName = userName;
		this.userHeadUrl = userHeadUrl;
		this.replyUserId = replyUserId;
		this.replyUserName = replyUserName;
		this.replyUserHeadUrl = replyUserHeadUrl;
		this.commentText = commentText;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feed_id")
	public ImFeed getImFeed() {
		return this.imFeed;
	}

	public void setImFeed(ImFeed imFeed) {
		this.imFeed = imFeed;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_head_url")
	public String getUserHeadUrl() {
		return this.userHeadUrl;
	}

	public void setUserHeadUrl(String userHeadUrl) {
		this.userHeadUrl = userHeadUrl;
	}

	@Column(name = "reply_user_id")
	public Long getReplyUserId() {
		return this.replyUserId;
	}

	public void setReplyUserId(Long replyUserId) {
		this.replyUserId = replyUserId;
	}

	@Column(name = "reply_user_name")
	public String getReplyUserName() {
		return this.replyUserName;
	}

	public void setReplyUserName(String replyUserName) {
		this.replyUserName = replyUserName;
	}

	@Column(name = "reply_user_head_url")
	public String getReplyUserHeadUrl() {
		return this.replyUserHeadUrl;
	}

	public void setReplyUserHeadUrl(String replyUserHeadUrl) {
		this.replyUserHeadUrl = replyUserHeadUrl;
	}

	@Column(name = "comment_text", length = 65535)
	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

}
