package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImFeedPraise generated by hbm2java
 */
@Entity
@Table(name = "im_feed_praise", catalog = "imdb")
public class ImFeedPraise implements java.io.Serializable {

	private Long id;
	private ImFeed imFeed;
	private Long userId;
	private String userName;
	private String userHeadUrl;
	private Long createTime;

	public ImFeedPraise() {
	}

	public ImFeedPraise(ImFeed imFeed, Long userId, String userName, String userHeadUrl, Long createTime) {
		this.imFeed = imFeed;
		this.userId = userId;
		this.userName = userName;
		this.userHeadUrl = userHeadUrl;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feed_id")
	public ImFeed getImFeed() {
		return this.imFeed;
	}

	public void setImFeed(ImFeed imFeed) {
		this.imFeed = imFeed;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_head_url")
	public String getUserHeadUrl() {
		return this.userHeadUrl;
	}

	public void setUserHeadUrl(String userHeadUrl) {
		this.userHeadUrl = userHeadUrl;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

}
