package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImFriendView generated by hbm2java
 */
@Entity
@Table(name = "im_friend_view", catalog = "imdb")
public class ImFriendView implements java.io.Serializable {

	private ImFriendViewId id;

	public ImFriendView() {
	}

	public ImFriendView(ImFriendViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userId")),
			@AttributeOverride(name = "remark", column = @Column(name = "remark")),
			@AttributeOverride(name = "isBlack", column = @Column(name = "isBlack")),
			@AttributeOverride(name = "receiveTip", column = @Column(name = "receiveTip")),
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name")),
			@AttributeOverride(name = "nickName", column = @Column(name = "nickName")),
			@AttributeOverride(name = "mobile", column = @Column(name = "mobile")),
			@AttributeOverride(name = "mail", column = @Column(name = "mail")),
			@AttributeOverride(name = "sex", column = @Column(name = "sex", length = 11)),
			@AttributeOverride(name = "birthday", column = @Column(name = "birthday")),
			@AttributeOverride(name = "sign", column = @Column(name = "sign")),
			@AttributeOverride(name = "province", column = @Column(name = "province", length = 11)),
			@AttributeOverride(name = "isOnline", column = @Column(name = "isOnline")),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 11)),
			@AttributeOverride(name = "district", column = @Column(name = "district", length = 11)),
			@AttributeOverride(name = "createTime", column = @Column(name = "createTime")),
			@AttributeOverride(name = "status", column = @Column(name = "status")),
			@AttributeOverride(name = "detail", column = @Column(name = "detail")),
			@AttributeOverride(name = "headUrl", column = @Column(name = "headUrl", length = 65535)) })
	public ImFriendViewId getId() {
		return this.id;
	}

	public void setId(ImFriendViewId id) {
		this.id = id;
	}

}
