package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImFriendBaseView generated by hbm2java
 */
@Entity
@Table(name = "im_friend_base_view", catalog = "imdb")
public class ImFriendBaseView implements java.io.Serializable {

	private ImFriendBaseViewId id;

	public ImFriendBaseView() {
	}

	public ImFriendBaseView(ImFriendBaseViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userId")),
			@AttributeOverride(name = "friendId", column = @Column(name = "friendId")),
			@AttributeOverride(name = "name", column = @Column(name = "NAME")),
			@AttributeOverride(name = "headUrl", column = @Column(name = "headUrl", length = 65535)) })
	public ImFriendBaseViewId getId() {
		return this.id;
	}

	public void setId(ImFriendBaseViewId id) {
		this.id = id;
	}

}
