package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImFriendViewId generated by hbm2java
 */
@Embeddable
public class ImFriendViewId implements java.io.Serializable {

	private Long userId;
	private String remark;
	private Integer isBlack;
	private Integer receiveTip;
	private Long id;
	private String name;
	private String nickName;
	private String mobile;
	private String mail;
	private String sex;
	private Long birthday;
	private String sign;
	private String province;
	private Integer isOnline;
	private String city;
	private String district;
	private Long createTime;
	private Integer status;
	private String detail;
	private String headUrl;

	public ImFriendViewId() {
	}

	public ImFriendViewId(Long userId, String remark, Integer isBlack, Integer receiveTip, Long id, String name,
			String nickName, String mobile, String mail, String sex, Long birthday, String sign, String province,
			Integer isOnline, String city, String district, Long createTime, Integer status, String detail,
			String headUrl) {
		this.userId = userId;
		this.remark = remark;
		this.isBlack = isBlack;
		this.receiveTip = receiveTip;
		this.id = id;
		this.name = name;
		this.nickName = nickName;
		this.mobile = mobile;
		this.mail = mail;
		this.sex = sex;
		this.birthday = birthday;
		this.sign = sign;
		this.province = province;
		this.isOnline = isOnline;
		this.city = city;
		this.district = district;
		this.createTime = createTime;
		this.status = status;
		this.detail = detail;
		this.headUrl = headUrl;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "isBlack")
	public Integer getIsBlack() {
		return this.isBlack;
	}

	public void setIsBlack(Integer isBlack) {
		this.isBlack = isBlack;
	}

	@Column(name = "receiveTip")
	public Integer getReceiveTip() {
		return this.receiveTip;
	}

	public void setReceiveTip(Integer receiveTip) {
		this.receiveTip = receiveTip;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nickName")
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "mail")
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "sex", length = 11)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "birthday")
	public Long getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Long birthday) {
		this.birthday = birthday;
	}

	@Column(name = "sign")
	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	@Column(name = "province", length = 11)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "isOnline")
	public Integer getIsOnline() {
		return this.isOnline;
	}

	public void setIsOnline(Integer isOnline) {
		this.isOnline = isOnline;
	}

	@Column(name = "city", length = 11)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district", length = 11)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "createTime")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "detail")
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "headUrl", length = 65535)
	public String getHeadUrl() {
		return this.headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImFriendViewId))
			return false;
		ImFriendViewId castOther = (ImFriendViewId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())))
				&& ((this.getIsBlack() == castOther.getIsBlack()) || (this.getIsBlack() != null
						&& castOther.getIsBlack() != null && this.getIsBlack().equals(castOther.getIsBlack())))
				&& ((this.getReceiveTip() == castOther.getReceiveTip()) || (this.getReceiveTip() != null
						&& castOther.getReceiveTip() != null && this.getReceiveTip().equals(castOther.getReceiveTip())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getNickName() == castOther.getNickName()) || (this.getNickName() != null
						&& castOther.getNickName() != null && this.getNickName().equals(castOther.getNickName())))
				&& ((this.getMobile() == castOther.getMobile()) || (this.getMobile() != null
						&& castOther.getMobile() != null && this.getMobile().equals(castOther.getMobile())))
				&& ((this.getMail() == castOther.getMail()) || (this.getMail() != null && castOther.getMail() != null
						&& this.getMail().equals(castOther.getMail())))
				&& ((this.getSex() == castOther.getSex()) || (this.getSex() != null && castOther.getSex() != null
						&& this.getSex().equals(castOther.getSex())))
				&& ((this.getBirthday() == castOther.getBirthday()) || (this.getBirthday() != null
						&& castOther.getBirthday() != null && this.getBirthday().equals(castOther.getBirthday())))
				&& ((this.getSign() == castOther.getSign()) || (this.getSign() != null && castOther.getSign() != null
						&& this.getSign().equals(castOther.getSign())))
				&& ((this.getProvince() == castOther.getProvince()) || (this.getProvince() != null
						&& castOther.getProvince() != null && this.getProvince().equals(castOther.getProvince())))
				&& ((this.getIsOnline() == castOther.getIsOnline()) || (this.getIsOnline() != null
						&& castOther.getIsOnline() != null && this.getIsOnline().equals(castOther.getIsOnline())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getDistrict() == castOther.getDistrict()) || (this.getDistrict() != null
						&& castOther.getDistrict() != null && this.getDistrict().equals(castOther.getDistrict())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this.getCreateTime() != null
						&& castOther.getCreateTime() != null && this.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getDetail() == castOther.getDetail()) || (this.getDetail() != null
						&& castOther.getDetail() != null && this.getDetail().equals(castOther.getDetail())))
				&& ((this.getHeadUrl() == castOther.getHeadUrl()) || (this.getHeadUrl() != null
						&& castOther.getHeadUrl() != null && this.getHeadUrl().equals(castOther.getHeadUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37 * result + (getIsBlack() == null ? 0 : this.getIsBlack().hashCode());
		result = 37 * result + (getReceiveTip() == null ? 0 : this.getReceiveTip().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getNickName() == null ? 0 : this.getNickName().hashCode());
		result = 37 * result + (getMobile() == null ? 0 : this.getMobile().hashCode());
		result = 37 * result + (getMail() == null ? 0 : this.getMail().hashCode());
		result = 37 * result + (getSex() == null ? 0 : this.getSex().hashCode());
		result = 37 * result + (getBirthday() == null ? 0 : this.getBirthday().hashCode());
		result = 37 * result + (getSign() == null ? 0 : this.getSign().hashCode());
		result = 37 * result + (getProvince() == null ? 0 : this.getProvince().hashCode());
		result = 37 * result + (getIsOnline() == null ? 0 : this.getIsOnline().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getDistrict() == null ? 0 : this.getDistrict().hashCode());
		result = 37 * result + (getCreateTime() == null ? 0 : this.getCreateTime().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getDetail() == null ? 0 : this.getDetail().hashCode());
		result = 37 * result + (getHeadUrl() == null ? 0 : this.getHeadUrl().hashCode());
		return result;
	}

}
