package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImFriendBaseViewId generated by hbm2java
 */
@Embeddable
public class ImFriendBaseViewId implements java.io.Serializable {

	private Long userId;
	private Long friendId;
	private String name;
	private String headUrl;

	public ImFriendBaseViewId() {
	}

	public ImFriendBaseViewId(Long userId, Long friendId, String name, String headUrl) {
		this.userId = userId;
		this.friendId = friendId;
		this.name = name;
		this.headUrl = headUrl;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "friendId")
	public Long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "headUrl", length = 65535)
	public String getHeadUrl() {
		return this.headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImFriendBaseViewId))
			return false;
		ImFriendBaseViewId castOther = (ImFriendBaseViewId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getFriendId() == castOther.getFriendId()) || (this.getFriendId() != null
						&& castOther.getFriendId() != null && this.getFriendId().equals(castOther.getFriendId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getHeadUrl() == castOther.getHeadUrl()) || (this.getHeadUrl() != null
						&& castOther.getHeadUrl() != null && this.getHeadUrl().equals(castOther.getHeadUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getFriendId() == null ? 0 : this.getFriendId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getHeadUrl() == null ? 0 : this.getHeadUrl().hashCode());
		return result;
	}

}
