package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImFriend generated by hbm2java
 */
@Entity
@Table(name = "im_friend", catalog = "imdb")
public class ImFriend implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long friendId;
	private String remark;
	private Long createrId;
	private Long createTime;
	private Integer isBlack;
	private Integer isFriend;
	private Integer receiveTip;

	public ImFriend() {
	}

	public ImFriend(Long userId, Long friendId, String remark, Long createrId, Long createTime, Integer isBlack,
			Integer isFriend, Integer receiveTip) {
		this.userId = userId;
		this.friendId = friendId;
		this.remark = remark;
		this.createrId = createrId;
		this.createTime = createTime;
		this.isBlack = isBlack;
		this.isFriend = isFriend;
		this.receiveTip = receiveTip;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "friendId")
	public Long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "createrId")
	public Long getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(Long createrId) {
		this.createrId = createrId;
	}

	@Column(name = "createTime")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "isBlack")
	public Integer getIsBlack() {
		return this.isBlack;
	}

	public void setIsBlack(Integer isBlack) {
		this.isBlack = isBlack;
	}

	@Column(name = "isFriend")
	public Integer getIsFriend() {
		return this.isFriend;
	}

	public void setIsFriend(Integer isFriend) {
		this.isFriend = isFriend;
	}

	@Column(name = "receiveTip")
	public Integer getReceiveTip() {
		return this.receiveTip;
	}

	public void setReceiveTip(Integer receiveTip) {
		this.receiveTip = receiveTip;
	}

}
