package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImMessageView generated by hbm2java
 */
@Entity
@Table(name = "im_message_view", catalog = "imdb")
public class ImMessageView implements java.io.Serializable {

	private ImMessageViewId id;

	public ImMessageView() {
	}

	public ImMessageView(ImMessageViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "belongId", column = @Column(name = "belongId")),
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "devType", column = @Column(name = "devType")),
			@AttributeOverride(name = "geoId", column = @Column(name = "geoId")),
			@AttributeOverride(name = "msgId", column = @Column(name = "msgId")),
			@AttributeOverride(name = "fromId", column = @Column(name = "fromId")),
			@AttributeOverride(name = "fromType", column = @Column(name = "fromType")),
			@AttributeOverride(name = "destId", column = @Column(name = "destId")),
			@AttributeOverride(name = "content", column = @Column(name = "content", length = 65535)),
			@AttributeOverride(name = "messageType", column = @Column(name = "messageType")),
			@AttributeOverride(name = "sendTime", column = @Column(name = "sendTime")),
			@AttributeOverride(name = "receiveTime", column = @Column(name = "receiveTime")),
			@AttributeOverride(name = "version", column = @Column(name = "version")),
			@AttributeOverride(name = "status", column = @Column(name = "status")) })
	public ImMessageViewId getId() {
		return this.id;
	}

	public void setId(ImMessageViewId id) {
		this.id = id;
	}

}
