package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ImMessageHistory generated by hbm2java
 */
@Entity
@Table(name = "im_message_history", catalog = "imdb")
public class ImMessageHistory implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Long belongUserId;
	private Integer devType;
	private Integer geoId;
	private String msgId;
	private Long fromId;
	private Integer fromType;
	private String imageIconUrl;
	private Long destId;
	private String fromName;
	private String content;
	private Integer messageType;
	private Long sendTime;
	private Long receiveTime;
	private Integer status;

	public ImMessageHistory() {
	}

	public ImMessageHistory(Long belongUserId, Integer devType, Integer geoId, String msgId, Long fromId,
			Integer fromType, String imageIconUrl, Long destId, String fromName, String content, Integer messageType,
			Long sendTime, Long receiveTime, Integer status) {
		this.belongUserId = belongUserId;
		this.devType = devType;
		this.geoId = geoId;
		this.msgId = msgId;
		this.fromId = fromId;
		this.fromType = fromType;
		this.imageIconUrl = imageIconUrl;
		this.destId = destId;
		this.fromName = fromName;
		this.content = content;
		this.messageType = messageType;
		this.sendTime = sendTime;
		this.receiveTime = receiveTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "belongUserId")
	public Long getBelongUserId() {
		return this.belongUserId;
	}

	public void setBelongUserId(Long belongUserId) {
		this.belongUserId = belongUserId;
	}

	@Column(name = "devType")
	public Integer getDevType() {
		return this.devType;
	}

	public void setDevType(Integer devType) {
		this.devType = devType;
	}

	@Column(name = "geoId")
	public Integer getGeoId() {
		return this.geoId;
	}

	public void setGeoId(Integer geoId) {
		this.geoId = geoId;
	}

	@Column(name = "msgId")
	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	@Column(name = "fromId")
	public Long getFromId() {
		return this.fromId;
	}

	public void setFromId(Long fromId) {
		this.fromId = fromId;
	}

	@Column(name = "fromType")
	public Integer getFromType() {
		return this.fromType;
	}

	public void setFromType(Integer fromType) {
		this.fromType = fromType;
	}

	@Column(name = "imageIconUrl")
	public String getImageIconUrl() {
		return this.imageIconUrl;
	}

	public void setImageIconUrl(String imageIconUrl) {
		this.imageIconUrl = imageIconUrl;
	}

	@Column(name = "destId")
	public Long getDestId() {
		return this.destId;
	}

	public void setDestId(Long destId) {
		this.destId = destId;
	}

	@Column(name = "fromName")
	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "messageType")
	public Integer getMessageType() {
		return this.messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	@Column(name = "sendTime")
	public Long getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Long sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "receiveTime")
	public Long getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Long receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
