package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImMessageViewId generated by hbm2java
 */
@Embeddable
public class ImMessageViewId implements java.io.Serializable {

	private Long belongId;
	private Long id;
	private Integer devType;
	private Integer geoId;
	private String msgId;
	private Long fromId;
	private Integer fromType;
	private Long destId;
	private String content;
	private Integer messageType;
	private Long sendTime;
	private Long receiveTime;
	private Integer version;
	private Integer status;

	public ImMessageViewId() {
	}

	public ImMessageViewId(Long belongId, Long id, Integer devType, Integer geoId, String msgId, Long fromId,
			Integer fromType, Long destId, String content, Integer messageType, Long sendTime, Long receiveTime,
			Integer version, Integer status) {
		this.belongId = belongId;
		this.id = id;
		this.devType = devType;
		this.geoId = geoId;
		this.msgId = msgId;
		this.fromId = fromId;
		this.fromType = fromType;
		this.destId = destId;
		this.content = content;
		this.messageType = messageType;
		this.sendTime = sendTime;
		this.receiveTime = receiveTime;
		this.version = version;
		this.status = status;
	}

	@Column(name = "belongId")
	public Long getBelongId() {
		return this.belongId;
	}

	public void setBelongId(Long belongId) {
		this.belongId = belongId;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "devType")
	public Integer getDevType() {
		return this.devType;
	}

	public void setDevType(Integer devType) {
		this.devType = devType;
	}

	@Column(name = "geoId")
	public Integer getGeoId() {
		return this.geoId;
	}

	public void setGeoId(Integer geoId) {
		this.geoId = geoId;
	}

	@Column(name = "msgId")
	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	@Column(name = "fromId")
	public Long getFromId() {
		return this.fromId;
	}

	public void setFromId(Long fromId) {
		this.fromId = fromId;
	}

	@Column(name = "fromType")
	public Integer getFromType() {
		return this.fromType;
	}

	public void setFromType(Integer fromType) {
		this.fromType = fromType;
	}

	@Column(name = "destId")
	public Long getDestId() {
		return this.destId;
	}

	public void setDestId(Long destId) {
		this.destId = destId;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "messageType")
	public Integer getMessageType() {
		return this.messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	@Column(name = "sendTime")
	public Long getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Long sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "receiveTime")
	public Long getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Long receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImMessageViewId))
			return false;
		ImMessageViewId castOther = (ImMessageViewId) other;

		return ((this.getBelongId() == castOther.getBelongId()) || (this.getBelongId() != null
				&& castOther.getBelongId() != null && this.getBelongId().equals(castOther.getBelongId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getDevType() == castOther.getDevType()) || (this.getDevType() != null
						&& castOther.getDevType() != null && this.getDevType().equals(castOther.getDevType())))
				&& ((this.getGeoId() == castOther.getGeoId()) || (this.getGeoId() != null
						&& castOther.getGeoId() != null && this.getGeoId().equals(castOther.getGeoId())))
				&& ((this.getMsgId() == castOther.getMsgId()) || (this.getMsgId() != null
						&& castOther.getMsgId() != null && this.getMsgId().equals(castOther.getMsgId())))
				&& ((this.getFromId() == castOther.getFromId()) || (this.getFromId() != null
						&& castOther.getFromId() != null && this.getFromId().equals(castOther.getFromId())))
				&& ((this.getFromType() == castOther.getFromType()) || (this.getFromType() != null
						&& castOther.getFromType() != null && this.getFromType().equals(castOther.getFromType())))
				&& ((this.getDestId() == castOther.getDestId()) || (this.getDestId() != null
						&& castOther.getDestId() != null && this.getDestId().equals(castOther.getDestId())))
				&& ((this.getContent() == castOther.getContent()) || (this.getContent() != null
						&& castOther.getContent() != null && this.getContent().equals(castOther.getContent())))
				&& ((this.getMessageType() == castOther.getMessageType())
						|| (this.getMessageType() != null && castOther.getMessageType() != null
								&& this.getMessageType().equals(castOther.getMessageType())))
				&& ((this.getSendTime() == castOther.getSendTime()) || (this.getSendTime() != null
						&& castOther.getSendTime() != null && this.getSendTime().equals(castOther.getSendTime())))
				&& ((this.getReceiveTime() == castOther.getReceiveTime())
						|| (this.getReceiveTime() != null && castOther.getReceiveTime() != null
								&& this.getReceiveTime().equals(castOther.getReceiveTime())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBelongId() == null ? 0 : this.getBelongId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getDevType() == null ? 0 : this.getDevType().hashCode());
		result = 37 * result + (getGeoId() == null ? 0 : this.getGeoId().hashCode());
		result = 37 * result + (getMsgId() == null ? 0 : this.getMsgId().hashCode());
		result = 37 * result + (getFromId() == null ? 0 : this.getFromId().hashCode());
		result = 37 * result + (getFromType() == null ? 0 : this.getFromType().hashCode());
		result = 37 * result + (getDestId() == null ? 0 : this.getDestId().hashCode());
		result = 37 * result + (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + (getMessageType() == null ? 0 : this.getMessageType().hashCode());
		result = 37 * result + (getSendTime() == null ? 0 : this.getSendTime().hashCode());
		result = 37 * result + (getReceiveTime() == null ? 0 : this.getReceiveTime().hashCode());
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
