package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImMenu generated by hbm2java
 */
@Entity
@Table(name = "im_menu", catalog = "imdb")
public class ImMenu implements java.io.Serializable {

	private Long id;
	private String name;
	private long pid;
	private short sort;
	private boolean isdisplay;
	private String m;
	private String c;
	private String a;
	private String icon;

	public ImMenu() {
	}

	public ImMenu(String name, long pid, short sort, boolean isdisplay, String m, String c, String a, String icon) {
		this.name = name;
		this.pid = pid;
		this.sort = sort;
		this.isdisplay = isdisplay;
		this.m = m;
		this.c = c;
		this.a = a;
		this.icon = icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid", nullable = false)
	public long getPid() {
		return this.pid;
	}

	public void setPid(long pid) {
		this.pid = pid;
	}

	@Column(name = "sort", nullable = false)
	public short getSort() {
		return this.sort;
	}

	public void setSort(short sort) {
		this.sort = sort;
	}

	@Column(name = "isdisplay", nullable = false)
	public boolean isIsdisplay() {
		return this.isdisplay;
	}

	public void setIsdisplay(boolean isdisplay) {
		this.isdisplay = isdisplay;
	}

	@Column(name = "m", nullable = false)
	public String getM() {
		return this.m;
	}

	public void setM(String m) {
		this.m = m;
	}

	@Column(name = "c", nullable = false)
	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	@Column(name = "a", nullable = false)
	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	@Column(name = "icon", nullable = false)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
