package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImMsgHistory generated by hbm2java
 */
@Entity
@Table(name = "im_msg_history", catalog = "imdb")
public class ImMsgHistory implements java.io.Serializable {

	private Long id;
	private Long belongId;
	private Long relationMsgId;

	public ImMsgHistory() {
	}

	public ImMsgHistory(Long belongId, Long relationMsgId) {
		this.belongId = belongId;
		this.relationMsgId = relationMsgId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "belongId")
	public Long getBelongId() {
		return this.belongId;
	}

	public void setBelongId(Long belongId) {
		this.belongId = belongId;
	}

	@Column(name = "relationMsgId")
	public Long getRelationMsgId() {
		return this.relationMsgId;
	}

	public void setRelationMsgId(Long relationMsgId) {
		this.relationMsgId = relationMsgId;
	}

}
