package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImNotice generated by hbm2java
 */
@Entity
@Table(name = "im_notice", catalog = "imdb")
public class ImNotice implements java.io.Serializable {

	private Long id;
	private String title;
	private String newsSrc;
	private Integer category;
	private String summary;
	private String content;
	private Long createTime;
	private Long readCount;
	private String previewImg;

	public ImNotice() {
	}

	public ImNotice(String title, String newsSrc, Integer category, String summary, String content, Long createTime,
			Long readCount, String previewImg) {
		this.title = title;
		this.newsSrc = newsSrc;
		this.category = category;
		this.summary = summary;
		this.content = content;
		this.createTime = createTime;
		this.readCount = readCount;
		this.previewImg = previewImg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "news_src")
	public String getNewsSrc() {
		return this.newsSrc;
	}

	public void setNewsSrc(String newsSrc) {
		this.newsSrc = newsSrc;
	}

	@Column(name = "category")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Column(name = "summary", length = 65535)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "read_count")
	public Long getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Long readCount) {
		this.readCount = readCount;
	}

	@Column(name = "preview_img")
	public String getPreviewImg() {
		return this.previewImg;
	}

	public void setPreviewImg(String previewImg) {
		this.previewImg = previewImg;
	}

}
