package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImPro generated by hbm2java
 */
@Entity
@Table(name = "im_pro", catalog = "imdb")
public class ImPro implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String agrNo;
	private Long serialNo;
	private String mobile;

	public ImPro() {
	}

	public ImPro(Long userId, String agrNo, Long serialNo, String mobile) {
		this.userId = userId;
		this.agrNo = agrNo;
		this.serialNo = serialNo;
		this.mobile = mobile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "agrNo", length = 30)
	public String getAgrNo() {
		return this.agrNo;
	}

	public void setAgrNo(String agrNo) {
		this.agrNo = agrNo;
	}

	@Column(name = "serialNo")
	public Long getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Long serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
