package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImRelation generated by hbm2java
 */
@Entity
@Table(name = "im_relation", catalog = "imdb")
public class ImRelation implements java.io.Serializable {

	private Long id;
	private Long userid;
	private String mobile;
	private Integer createtime;
	private Integer exptime;

	public ImRelation() {
	}

	public ImRelation(Long userid, String mobile, Integer createtime, Integer exptime) {
		this.userid = userid;
		this.mobile = mobile;
		this.createtime = createtime;
		this.exptime = exptime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userid")
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "createtime")
	public Integer getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Integer createtime) {
		this.createtime = createtime;
	}

	@Column(name = "exptime")
	public Integer getExptime() {
		return this.exptime;
	}

	public void setExptime(Integer exptime) {
		this.exptime = exptime;
	}

}
