package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImRedpacketHistory generated by hbm2java
 */
@Entity
@Table(name = "im_redpacket_history", catalog = "imdb")
public class ImRedpacketHistory implements java.io.Serializable {

	private Long id;
	private Long redPacketId;
	private Long userId;
	private BigDecimal amount;
	private Long createTime;

	public ImRedpacketHistory() {
	}

	public ImRedpacketHistory(Long redPacketId, Long userId, BigDecimal amount, Long createTime) {
		this.redPacketId = redPacketId;
		this.userId = userId;
		this.amount = amount;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "redPacketId")
	public Long getRedPacketId() {
		return this.redPacketId;
	}

	public void setRedPacketId(Long redPacketId) {
		this.redPacketId = redPacketId;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "createTime")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

}
