package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImRockViewId generated by hbm2java
 */
@Embeddable
public class ImRockViewId implements java.io.Serializable {

	private long userid;
	private String lat;
	private String lng;
	private int updatetime;
	private String sex;
	private String headUrl;
	private String name;

	public ImRockViewId() {
	}

	public ImRockViewId(long userid, String lat, String lng, int updatetime) {
		this.userid = userid;
		this.lat = lat;
		this.lng = lng;
		this.updatetime = updatetime;
	}

	public ImRockViewId(long userid, String lat, String lng, int updatetime, String sex, String headUrl, String name) {
		this.userid = userid;
		this.lat = lat;
		this.lng = lng;
		this.updatetime = updatetime;
		this.sex = sex;
		this.headUrl = headUrl;
		this.name = name;
	}

	@Column(name = "userid", nullable = false)
	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	@Column(name = "lat", nullable = false, length = 50)
	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	@Column(name = "lng", nullable = false, length = 50)
	public String getLng() {
		return this.lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	@Column(name = "updatetime", nullable = false)
	public int getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(int updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "sex", length = 11)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "headUrl", length = 65535)
	public String getHeadUrl() {
		return this.headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImRockViewId))
			return false;
		ImRockViewId castOther = (ImRockViewId) other;

		return (this.getUserid() == castOther.getUserid()) && ((this.getLat() == castOther.getLat())
				|| (this.getLat() != null && castOther.getLat() != null && this.getLat().equals(castOther.getLat())))
				&& ((this.getLng() == castOther.getLng()) || (this.getLng() != null && castOther.getLng() != null
						&& this.getLng().equals(castOther.getLng())))
				&& (this.getUpdatetime() == castOther.getUpdatetime())
				&& ((this.getSex() == castOther.getSex()) || (this.getSex() != null && castOther.getSex() != null
						&& this.getSex().equals(castOther.getSex())))
				&& ((this.getHeadUrl() == castOther.getHeadUrl()) || (this.getHeadUrl() != null
						&& castOther.getHeadUrl() != null && this.getHeadUrl().equals(castOther.getHeadUrl())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserid();
		result = 37 * result + (getLat() == null ? 0 : this.getLat().hashCode());
		result = 37 * result + (getLng() == null ? 0 : this.getLng().hashCode());
		result = 37 * result + this.getUpdatetime();
		result = 37 * result + (getSex() == null ? 0 : this.getSex().hashCode());
		result = 37 * result + (getHeadUrl() == null ? 0 : this.getHeadUrl().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
