package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImShareReplyViewId generated by hbm2java
 */
@Embeddable
public class ImShareReplyViewId implements java.io.Serializable {

	private long id;
	private Long sid;
	private Long userId;
	private Long fuserId;
	private String content;
	private Long createtime;
	private Boolean type;
	private String unickname;
	private String fnickname;

	public ImShareReplyViewId() {
	}

	public ImShareReplyViewId(long id) {
		this.id = id;
	}

	public ImShareReplyViewId(long id, Long sid, Long userId, Long fuserId, String content, Long createtime,
			Boolean type, String unickname, String fnickname) {
		this.id = id;
		this.sid = sid;
		this.userId = userId;
		this.fuserId = fuserId;
		this.content = content;
		this.createtime = createtime;
		this.type = type;
		this.unickname = unickname;
		this.fnickname = fnickname;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "sid")
	public Long getSid() {
		return this.sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "fuserId")
	public Long getFuserId() {
		return this.fuserId;
	}

	public void setFuserId(Long fuserId) {
		this.fuserId = fuserId;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "createtime")
	public Long getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "unickname")
	public String getUnickname() {
		return this.unickname;
	}

	public void setUnickname(String unickname) {
		this.unickname = unickname;
	}

	@Column(name = "fnickname")
	public String getFnickname() {
		return this.fnickname;
	}

	public void setFnickname(String fnickname) {
		this.fnickname = fnickname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImShareReplyViewId))
			return false;
		ImShareReplyViewId castOther = (ImShareReplyViewId) other;

		return (this.getId() == castOther.getId()) && ((this.getSid() == castOther.getSid())
				|| (this.getSid() != null && castOther.getSid() != null && this.getSid().equals(castOther.getSid())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getFuserId() == castOther.getFuserId()) || (this.getFuserId() != null
						&& castOther.getFuserId() != null && this.getFuserId().equals(castOther.getFuserId())))
				&& ((this.getContent() == castOther.getContent()) || (this.getContent() != null
						&& castOther.getContent() != null && this.getContent().equals(castOther.getContent())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getUnickname() == castOther.getUnickname()) || (this.getUnickname() != null
						&& castOther.getUnickname() != null && this.getUnickname().equals(castOther.getUnickname())))
				&& ((this.getFnickname() == castOther.getFnickname()) || (this.getFnickname() != null
						&& castOther.getFnickname() != null && this.getFnickname().equals(castOther.getFnickname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getSid() == null ? 0 : this.getSid().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getFuserId() == null ? 0 : this.getFuserId().hashCode());
		result = 37 * result + (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getUnickname() == null ? 0 : this.getUnickname().hashCode());
		result = 37 * result + (getFnickname() == null ? 0 : this.getFnickname().hashCode());
		return result;
	}

}
