package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImShareView generated by hbm2java
 */
@Entity
@Table(name = "im_share_view", catalog = "imdb")
public class ImShareView implements java.io.Serializable {

	private ImShareViewId id;

	public ImShareView() {
	}

	public ImShareView(ImShareViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sid", column = @Column(name = "sid", nullable = false)),
			@AttributeOverride(name = "uid", column = @Column(name = "uid")),
			@AttributeOverride(name = "content", column = @Column(name = "content", nullable = false, length = 65535)),
			@AttributeOverride(name = "createtime", column = @Column(name = "createtime")),
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "atwho", column = @Column(name = "atwho", nullable = false, length = 65535)),
			@AttributeOverride(name = "nickName", column = @Column(name = "nickName")),
			@AttributeOverride(name = "headUrl", column = @Column(name = "headUrl", length = 65535)),
			@AttributeOverride(name = "praises", column = @Column(name = "praises")),
			@AttributeOverride(name = "replys", column = @Column(name = "replys")) })
	public ImShareViewId getId() {
		return this.id;
	}

	public void setId(ImShareViewId id) {
		this.id = id;
	}

}
