package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImShare generated by hbm2java
 */
@Entity
@Table(name = "im_share", catalog = "imdb")
public class ImShare implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String content;
	private Long createtime;
	private Short type;
	private String atwho;
	private String pics;

	public ImShare() {
	}

	public ImShare(String content, String atwho, String pics) {
		this.content = content;
		this.atwho = atwho;
		this.pics = pics;
	}

	public ImShare(Long userId, String content, Long createtime, Short type, String atwho, String pics) {
		this.userId = userId;
		this.content = content;
		this.createtime = createtime;
		this.type = type;
		this.atwho = atwho;
		this.pics = pics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "createtime")
	public Long getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	@Column(name = "type")
	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	@Column(name = "atwho", nullable = false, length = 65535)
	public String getAtwho() {
		return this.atwho;
	}

	public void setAtwho(String atwho) {
		this.atwho = atwho;
	}

	@Column(name = "pics", nullable = false, length = 65535)
	public String getPics() {
		return this.pics;
	}

	public void setPics(String pics) {
		this.pics = pics;
	}

}
