package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImShareReplyView generated by hbm2java
 */
@Entity
@Table(name = "im_share_reply_view", catalog = "imdb")
public class ImShareReplyView implements java.io.Serializable {

	private ImShareReplyViewId id;

	public ImShareReplyView() {
	}

	public ImShareReplyView(ImShareReplyViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "sid", column = @Column(name = "sid")),
			@AttributeOverride(name = "userId", column = @Column(name = "userId")),
			@AttributeOverride(name = "fuserId", column = @Column(name = "fuserId")),
			@AttributeOverride(name = "content", column = @Column(name = "content", length = 65535)),
			@AttributeOverride(name = "createtime", column = @Column(name = "createtime")),
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "unickname", column = @Column(name = "unickname")),
			@AttributeOverride(name = "fnickname", column = @Column(name = "fnickname")) })
	public ImShareReplyViewId getId() {
		return this.id;
	}

	public void setId(ImShareReplyViewId id) {
		this.id = id;
	}

}
