package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImShareViewId generated by hbm2java
 */
@Embeddable
public class ImShareViewId implements java.io.Serializable {

	private long sid;
	private Long uid;
	private String content;
	private Long createtime;
	private Short type;
	private String atwho;
	private String nickName;
	private String headUrl;
	private Long praises;
	private Long replys;

	public ImShareViewId() {
	}

	public ImShareViewId(long sid, String content, String atwho) {
		this.sid = sid;
		this.content = content;
		this.atwho = atwho;
	}

	public ImShareViewId(long sid, Long uid, String content, Long createtime, Short type, String atwho, String nickName,
			String headUrl, Long praises, Long replys) {
		this.sid = sid;
		this.uid = uid;
		this.content = content;
		this.createtime = createtime;
		this.type = type;
		this.atwho = atwho;
		this.nickName = nickName;
		this.headUrl = headUrl;
		this.praises = praises;
		this.replys = replys;
	}

	@Column(name = "sid", nullable = false)
	public long getSid() {
		return this.sid;
	}

	public void setSid(long sid) {
		this.sid = sid;
	}

	@Column(name = "uid")
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "createtime")
	public Long getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	@Column(name = "type")
	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	@Column(name = "atwho", nullable = false, length = 65535)
	public String getAtwho() {
		return this.atwho;
	}

	public void setAtwho(String atwho) {
		this.atwho = atwho;
	}

	@Column(name = "nickName")
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "headUrl", length = 65535)
	public String getHeadUrl() {
		return this.headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	@Column(name = "praises")
	public Long getPraises() {
		return this.praises;
	}

	public void setPraises(Long praises) {
		this.praises = praises;
	}

	@Column(name = "replys")
	public Long getReplys() {
		return this.replys;
	}

	public void setReplys(Long replys) {
		this.replys = replys;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImShareViewId))
			return false;
		ImShareViewId castOther = (ImShareViewId) other;

		return (this.getSid() == castOther.getSid()) && ((this.getUid() == castOther.getUid())
				|| (this.getUid() != null && castOther.getUid() != null && this.getUid().equals(castOther.getUid())))
				&& ((this.getContent() == castOther.getContent()) || (this.getContent() != null
						&& castOther.getContent() != null && this.getContent().equals(castOther.getContent())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getAtwho() == castOther.getAtwho()) || (this.getAtwho() != null
						&& castOther.getAtwho() != null && this.getAtwho().equals(castOther.getAtwho())))
				&& ((this.getNickName() == castOther.getNickName()) || (this.getNickName() != null
						&& castOther.getNickName() != null && this.getNickName().equals(castOther.getNickName())))
				&& ((this.getHeadUrl() == castOther.getHeadUrl()) || (this.getHeadUrl() != null
						&& castOther.getHeadUrl() != null && this.getHeadUrl().equals(castOther.getHeadUrl())))
				&& ((this.getPraises() == castOther.getPraises()) || (this.getPraises() != null
						&& castOther.getPraises() != null && this.getPraises().equals(castOther.getPraises())))
				&& ((this.getReplys() == castOther.getReplys()) || (this.getReplys() != null
						&& castOther.getReplys() != null && this.getReplys().equals(castOther.getReplys())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSid();
		result = 37 * result + (getUid() == null ? 0 : this.getUid().hashCode());
		result = 37 * result + (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getAtwho() == null ? 0 : this.getAtwho().hashCode());
		result = 37 * result + (getNickName() == null ? 0 : this.getNickName().hashCode());
		result = 37 * result + (getHeadUrl() == null ? 0 : this.getHeadUrl().hashCode());
		result = 37 * result + (getPraises() == null ? 0 : this.getPraises().hashCode());
		result = 37 * result + (getReplys() == null ? 0 : this.getReplys().hashCode());
		return result;
	}

}
