package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImTop generated by hbm2java
 */
@Entity
@Table(name = "im_top", catalog = "imdb")
public class ImTop implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Integer destType;
	private Long destId;

	public ImTop() {
	}

	public ImTop(Long userId, Integer destType, Long destId) {
		this.userId = userId;
		this.destType = destType;
		this.destId = destId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "destType")
	public Integer getDestType() {
		return this.destType;
	}

	public void setDestType(Integer destType) {
		this.destType = destType;
	}

	@Column(name = "destId")
	public Long getDestId() {
		return this.destId;
	}

	public void setDestId(Long destId) {
		this.destId = destId;
	}

}
