package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImTransform generated by hbm2java
 */
@Entity
@Table(name = "im_transform", catalog = "imdb")
public class ImTransform implements java.io.Serializable {

	private Long id;
	private long userId;
	private long destId;
	private BigDecimal amount;
	private String msg;
	private int status;
	private long sendTime;
	private Long confirmTime;

	public ImTransform() {
	}

	public ImTransform(long userId, long destId, BigDecimal amount, int status, long sendTime) {
		this.userId = userId;
		this.destId = destId;
		this.amount = amount;
		this.status = status;
		this.sendTime = sendTime;
	}

	public ImTransform(long userId, long destId, BigDecimal amount, String msg, int status, long sendTime,
			Long confirmTime) {
		this.userId = userId;
		this.destId = destId;
		this.amount = amount;
		this.msg = msg;
		this.status = status;
		this.sendTime = sendTime;
		this.confirmTime = confirmTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "destId", nullable = false)
	public long getDestId() {
		return this.destId;
	}

	public void setDestId(long destId) {
		this.destId = destId;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "msg")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "sendTime", nullable = false)
	public long getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(long sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "confirmTime")
	public Long getConfirmTime() {
		return this.confirmTime;
	}

	public void setConfirmTime(Long confirmTime) {
		this.confirmTime = confirmTime;
	}

}
