package com.yx.base.model;
// Generated 2018-1-28 22:30:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImVersion generated by hbm2java
 */
@Entity
@Table(name = "im_version", catalog = "imdb")
public class ImVersion implements java.io.Serializable {

	private Long id;
	private String versions;
	private String content;
	private Integer device;
	private String url;

	public ImVersion() {
	}

	public ImVersion(String versions, String content, Integer device, String url) {
		this.versions = versions;
		this.content = content;
		this.device = device;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "versions")
	public String getVersions() {
		return this.versions;
	}

	public void setVersions(String versions) {
		this.versions = versions;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "device")
	public Integer getDevice() {
		return this.device;
	}

	public void setDevice(Integer device) {
		this.device = device;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
